[php]
# Ensure GD extension is installed for phpspreadsheet
extensions = ["ctype", "curl", "dom", "fileinfo", "filter", "hash", "mbstring", "openssl", "pcre", "pdo", "session", "tokenizer", "xml", "pdo_pgsql", "gd", "zip"]
